Repository lexicongovernance/pluraltools-frontend, pull requests merged in 2024-08, with the labels that each got.

#711 add case when no fields exists
  packages/berlin/src/pages/Register.tsx
Labels: bug

#716 update groups reg to be under event url
  packages/berlin/src/App.tsx
Labels: bug

#730 fix initial step bug on registration
  packages/berlin/src/components/header/Header.tsx
  packages/berlin/src/pages/Register.tsx
Labels: bug

#732 731 update event page
  packages/api/src/types/Events.ts
  packages/berlin/src/components/events/Events.tsx
  packages/berlin/src/pages/Events.tsx
Labels: improvement

#738 735 better tab error message
  packages/berlin/src/components/cycles/Cycles.tsx
  packages/berlin/src/pages/Event.tsx
Labels: improvement

#740 landing page changes
  packages/berlin/src/components/header/Header.tsx
  packages/berlin/src/components/zupass-button/ZupassLoginButton.tsx
  packages/berlin/src/pages/Landing.tsx
Labels: edge-esmeralda

#741 fix zupass button formatting
  packages/berlin/src/components/header/Header.tsx
  packages/berlin/src/components/zupass-button/ZupassLoginButton.tsx
Labels: bug

#739 Add cursor pointer to comments icon
  packages/berlin/src/components/option/Option.tsx
Labels: improvement

#743 Update group registration text
  packages/berlin/src/pages/Register.tsx
Labels: edge-esmeralda

#745 Add skeleton to events main
  packages/berlin/src/components/skeleton/Skeleton.tsx
  packages/berlin/src/components/skeleton/index.ts
  packages/berlin/src/pages/Event.tsx
Labels: feature

#747 fix always false statement to check if values are not defined
  packages/berlin/src/pages/Register.tsx
Labels: bug
