Repository lexicongovernance/pluraltools-frontend, pull requests merged in 2024-07, with the labels that each got.

#656 655 support markdown at develop
  .github/workflows/check-formatting.yml
  .github/workflows/lint.yml
  packages/berlin/src/components/option-card/OptionCard.tsx
  packages/berlin/src/components/tables/results-table/ResultsTable.tsx
Labels: improvement

#652 648 delete comment button
  packages/berlin/src/components/option-card/OptionCard.tsx
  packages/berlin/src/components/tables/results-table/ResultsTable.tsx
  packages/berlin/src/pages/Cycle.tsx
  packages/berlin/src/pages/Results.tsx
Labels: DO NOT MERGE, edge-esmeralda

#653 651 remove my artefacts link from navbar
  packages/berlin/src/components/header/Header.tsx
  packages/berlin/src/pages/Event.tsx
Labels: edge-esmeralda

#654 647 check mardown support for registration field
  packages/berlin/src/components/option-card/OptionCard.tsx
  packages/berlin/src/components/tables/results-table/ResultsTable.tsx
Labels: edge-esmeralda

#645 644 bring shadcn to develop
  package.json
  packages/berlin/components.json
  packages/berlin/package.json
  packages/berlin/postcss.config.js
  packages/berlin/src/index.css
  packages/berlin/src/lib/utils.ts
  packages/berlin/src/main.tsx
  packages/berlin/tailwind.config.js
  packages/berlin/tsconfig.json
  packages/berlin/tsconfig.node.json
  packages/berlin/vite.config.ts
  pnpm-lock.yaml
  vite.config.ts
Labels: improvement, multi-event-support

#668 change header
  packages/berlin/src/data/header.ts
Labels: edge-esmeralda

#672 Update landing page
  packages/berlin/src/pages/Landing.tsx
Labels: edge-esmeralda

#673 Fix vote state
  packages/berlin/src/pages/Cycle.tsx
  packages/berlin/src/store/index.ts
  packages/berlin/src/utils/voting.ts
Labels: bug

#681 fix race conditions
  packages/berlin/src/components/carousel/Carousel.tsx
  packages/berlin/src/pages/Register.tsx
Labels: bug

#689 Add carousel
  package.json
  packages/berlin/package.json
  packages/berlin/src/_components/ui/badge.tsx
  packages/berlin/src/_components/ui/button.tsx
  packages/berlin/src/_components/ui/command.tsx
  packages/berlin/src/_components/ui/dialog.tsx
  packages/berlin/src/_components/ui/popover.tsx
  packages/berlin/src/_components/ui/separator.tsx
  packages/berlin/src/components/carousel/Carousel.tsx
  packages/berlin/src/components/carousel/index.ts
  packages/berlin/src/components/multi-select/MultiSelect.tsx
  packages/berlin/src/components/multi-select/index.ts
  packages/berlin/src/pages/Register.tsx
  pnpm-lock.yaml
Labels: feature

#696 Text fixes
  packages/berlin/src/pages/Register.tsx
Labels: hotifx

#697 change artefact to proposal (#696)
  packages/berlin/src/pages/Register.tsx
Labels: hotifx
