Repository lexicongovernance/pluraltools-frontend, pull requests merged in 2024-06, with the labels that each got.

#579 lock interactions
  packages/berlin/src/App.tsx
  packages/berlin/src/components/tables/groups-table/GroupsTable.tsx
  packages/berlin/src/components/tables/results-table/ResultsTable.tsx
  packages/berlin/src/pages/Account.tsx
  packages/berlin/src/pages/Comments.tsx
  packages/berlin/src/pages/PublicGroupRegistration.tsx
  packages/berlin/src/pages/Register.tsx
  packages/berlin/src/pages/Results.tsx
  packages/berlin/src/pages/SecretGroupRegistration.tsx
Labels: feature

#580 new landing page copy
  packages/berlin/src/pages/Landing.tsx
Labels: feature

#581 Show collaborators & Research output
  packages/berlin/src/components/tables/results-table/ResultsTable.tsx
Labels: berlin

#591 590 mobile cards agenda page
  packages/berlin/src/components/table/Table.styled.tsx
  packages/berlin/src/components/table/Table.tsx
  packages/berlin/src/pages/Event.tsx
Labels: feature, berlin

#589 586 remove fields from account page
  packages/api/src/types/UserType.ts
  packages/berlin/src/pages/Account.tsx
Labels: berlin

#595 refactor form fields
  packages/berlin/src/components/form/FormInput.tsx
  packages/berlin/src/components/form/NumberInput.tsx
  packages/berlin/src/components/form/SelectInput.tsx
  packages/berlin/src/components/form/TextAreaInput.tsx
  packages/berlin/src/components/form/TextInput.tsx
  packages/berlin/src/components/form/index.ts
  packages/berlin/src/components/textarea/Textarea.tsx
  packages/berlin/src/pages/Register.tsx
Labels: improvement

#593 592 mobile cards voting page
  packages/api/src/types/CycleType.ts
  packages/berlin/src/components/columns/cycle-columns/CycleColumns.styled.tsx
  packages/berlin/src/components/columns/cycle-columns/CycleColumns.tsx
  packages/berlin/src/components/event-card/EventCard.styled.tsx
  packages/berlin/src/components/event-card/EventCard.tsx
  packages/berlin/src/components/option-card/OptionCard.styled.tsx
  packages/berlin/src/components/option-card/OptionCard.tsx
  packages/berlin/src/pages/Cycle.tsx
  packages/berlin/src/pages/Event.tsx
Labels: berlin

#597 596 results card voting page
  packages/berlin/src/components/columns/results-columns/ResultsColumns.styled.tsx
  packages/berlin/src/components/tables/results-table/ResultsTable.styled.tsx
  packages/berlin/src/components/tables/results-table/ResultsTable.tsx
  packages/berlin/src/pages/Results.tsx
Labels: berlin

#605 fix select group value from id
  packages/berlin/src/pages/Register.tsx
Labels: bug

#606 Fix registration
  packages/api/src/types/CycleType.ts
  packages/berlin/src/components/form/NumberInput.tsx
  packages/berlin/src/components/form/TextAreaInput.tsx
  packages/berlin/src/components/form/TextInput.tsx
  packages/berlin/src/components/option-card/OptionCard.tsx
  packages/berlin/src/pages/Cycle.tsx
  packages/berlin/src/pages/Register.tsx
  packages/berlin/src/utils/validation.ts
Labels: bug

#610 609 two steps group registration form
  packages/berlin/src/components/dots/Dots.tsx
  packages/berlin/src/components/header/Header.tsx
  packages/berlin/src/pages/Onboarding.tsx
  packages/berlin/src/pages/Register.tsx
Labels: berlin

#611 Diego/small comment move to force vercel deployment
  packages/berlin/src/pages/Register.tsx
Labels: bug

#614 activate leave button
  packages/berlin/src/components/tables/groups-table/GroupsTable.tsx
Labels: feature

#613 612 fix alignment on voting page proposal
  packages/berlin/src/components/columns/cycle-columns/CycleColumns.styled.tsx
Labels: berlin

#615 update typescript version
  package.json
  pnpm-lock.yaml
Labels: improvement

#617 bring edge esmeralda back to frontend repo
  packages/berlin/src/components/header/Header.tsx
  packages/berlin/src/components/voting-cards/VotingCards.tsx
  packages/berlin/src/data/footer.ts
  packages/berlin/src/data/header.ts
  packages/berlin/src/layout/Layout.styled.tsx
  packages/berlin/src/layout/Layout.tsx
  packages/berlin/src/pages/Cycle.tsx
  packages/berlin/src/pages/Event.tsx
Labels: feature

#624 change index html
  packages/berlin/index.html
  packages/berlin/public/favicon.ico
  packages/berlin/src/data/header.ts
Labels: edge-esmeralda

#627 reduce number of hearts
  packages/berlin/src/utils/constants.ts
Labels: edge-esmeralda

#626 naming changes
  packages/berlin/src/components/columns/cycle-columns/CycleColumns.tsx
  packages/berlin/src/data/groups.ts
  packages/berlin/src/pages/Register.tsx
  packages/berlin/src/pages/Results.tsx
Labels: edge-esmeralda

#631 629 vote and result page changes
  packages/berlin/src/components/columns/cycle-columns/CycleColumns.styled.tsx
  packages/berlin/src/components/columns/cycle-columns/CycleColumns.tsx
  packages/berlin/src/components/option-card/OptionCard.tsx
  packages/berlin/src/components/tables/results-table/ResultsTable.tsx
  packages/berlin/src/pages/Comments.tsx
Labels: edge-esmeralda

#630 add hard coded multi select
  package.json
  packages/berlin/components.json
  packages/berlin/package.json
  packages/berlin/postcss.config.js
  packages/berlin/src/_components/ui/badge.tsx
  packages/berlin/src/_components/ui/button.tsx
  packages/berlin/src/_components/ui/command.tsx
  packages/berlin/src/_components/ui/dialog.tsx
  packages/berlin/src/_components/ui/popover.tsx
  packages/berlin/src/_components/ui/separator.tsx
  packages/berlin/src/components/multi-select/MultiSelect.tsx
  packages/berlin/src/index.css
  packages/berlin/src/lib/utils.ts
  packages/berlin/src/main.tsx
  packages/berlin/src/pages/Register.tsx
  packages/berlin/src/utils/constants.ts
  packages/berlin/tailwind.config.js
  packages/berlin/tsconfig.json
  packages/berlin/tsconfig.node.json
  packages/berlin/vite.config.ts
  pnpm-lock.yaml
  vite.config.ts
Labels: feature, edge-esmeralda

#632 618 landing page updates
  packages/berlin/components.json
  packages/berlin/src/_components/ui/badge.tsx
  packages/berlin/src/_components/ui/button.tsx
  packages/berlin/src/_components/ui/command.tsx
  packages/berlin/src/_components/ui/dialog.tsx
  packages/berlin/src/_components/ui/popover.tsx
  packages/berlin/src/_components/ui/separator.tsx
  packages/berlin/src/lib/utils.ts
  packages/berlin/src/pages/Landing.tsx
Labels: edge-esmeralda

#634 633 Removes funding from results onboarding
  packages/berlin/src/pages/Results.tsx
Labels: edge-esmeralda

#637 naming changes
  packages/berlin/src/components/columns/cycle-columns/CycleColumns.tsx
  packages/berlin/src/pages/Cycle.tsx
  packages/berlin/src/pages/Event.tsx
  packages/berlin/src/pages/Results.tsx
Labels: edge-esmeralda

#638 add label to multiselect
  packages/berlin/src/pages/Register.tsx
Labels: feature, edge-esmeralda

#636 Style changes
  .prettierrc.cjs
  package.json
  packages/berlin/src/_components/ui/command.tsx
  packages/berlin/src/components/multi-select/MultiSelect.tsx
  pnpm-lock.yaml
Labels: edge-esmeralda
