Repository lexicongovernance/pluraltools-frontend, pull requests merged in 2024-05, with the labels that each got.

#434 Save registration field option value
  packages/berlin/src/pages/Register.tsx
Labels: bug

#436 399 new group registrations shouldnt go to holding page
  packages/berlin/src/pages/Register.tsx
Labels: berlin

#441 424 adjust berlin results page UI to match other pages
  packages/api/src/types/ForumQuestionType.ts
  packages/berlin/public/icons/money-dark.svg
  packages/berlin/public/icons/money-light.svg
  packages/berlin/public/icons/sqrt-dark.svg
  packages/berlin/public/icons/sqrt-light.svg
  packages/berlin/src/components/cycle-columns/CycleColumns.styled.tsx
  packages/berlin/src/components/cycle-columns/CycleColumns.tsx
  packages/berlin/src/components/option-card/OptionCard.styled.tsx
  packages/berlin/src/components/option-card/OptionCard.tsx
  packages/berlin/src/components/result-card/ResultCard.styled.tsx
  packages/berlin/src/components/result-card/ResultCard.tsx
  packages/berlin/src/components/results-columns/ResultsColumns.styled.tsx
  packages/berlin/src/components/results-columns/ResultsColumns.tsx
  packages/berlin/src/components/results-columns/index.ts
  packages/berlin/src/components/stat-card/StatCard.styled.tsx
  packages/berlin/src/components/stat-card/StatCard.tsx
  packages/berlin/src/components/stat-card/index.ts
  packages/berlin/src/components/stats-card/StatsCard.styled.tsx
  packages/berlin/src/components/stats-card/StatsCard.tsx
  packages/berlin/src/components/stats-card/index.ts
  packages/berlin/src/components/stats-columns/StatsColumns.styled.tsx
  packages/berlin/src/components/stats-columns/StatsColumns.tsx
  packages/berlin/src/components/stats-columns/index.ts
  packages/berlin/src/pages/Comments.tsx
  packages/berlin/src/pages/Cycle.tsx
  packages/berlin/src/pages/Results.tsx
Labels: priority, berlin

#452 451 display option users at comments page
  packages/api/src/fetchOptionUsers.ts
  packages/api/src/index.ts
  packages/api/src/types/OptionUsersType.ts
  packages/berlin/src/pages/Comments.tsx
Labels: berlin

#458 437 adjust validation to mnemonics
  packages/berlin/src/pages/SecretGroupRegistration.tsx
Labels: bug, priority, berlin

#459 hide select when only none is the option
  packages/berlin/src/pages/Register.tsx
Labels: bug

#460 Improve save registration
  packages/berlin/src/pages/Register.tsx
Labels: bug

#461 Handle new redirect to holding
  packages/berlin/src/pages/Register.tsx
Labels: bug

#467 463 truncate seconds only show timer when 5 minutes are remaining
  packages/berlin/src/hooks/useCountdown.tsx
  packages/berlin/src/pages/Cycle.tsx
Labels: bug, berlin

#484 471 add proposals to navbar
  packages/berlin/public/icons/user-dark.svg
  packages/berlin/public/icons/user-light.svg
  packages/berlin/src/components/header/Header.tsx
Labels: feature, easy, berlin

#477 474 comment page button to save votes does not work
  packages/api/src/types/OptionUsersType.ts
  packages/berlin/src/components/header/Header.tsx
  packages/berlin/src/components/option-card/OptionCard.tsx
  packages/berlin/src/pages/Comments.tsx
  packages/berlin/src/pages/Cycle.tsx
  packages/berlin/src/utils/voting.ts
Labels: bug, berlin

#485 invalidate cache for groups when joining
  packages/berlin/src/components/tables/groups-table/GroupsTable.tsx
  packages/berlin/src/pages/PublicGroupRegistration.tsx
  packages/berlin/src/pages/SecretGroupRegistration.tsx
Labels: bug

#486 Improve join group error
  packages/api/src/deleteUsersToGroups.ts
  packages/api/src/postUsersToGroups.ts
  packages/api/src/putUsersToGroups.ts
  packages/berlin/src/components/tables/groups-table/GroupsTable.tsx
  packages/berlin/src/pages/Account.tsx
  packages/berlin/src/pages/PublicGroupRegistration.tsx
  packages/berlin/src/pages/SecretGroupRegistration.tsx
Labels: feature

#489 Fix members in group table
  packages/berlin/src/components/tables/groups-table/GroupsTable.tsx
  packages/berlin/src/pages/SecretGroupRegistration.tsx
Labels: bug

#481 478 implement text changes
  packages/berlin/src/components/dialog/Dialog.tsx
  packages/berlin/src/components/research-group-form/ResearchGroupForm.tsx
  packages/berlin/src/components/secret-code/SecretCode.tsx
  packages/berlin/src/data/groups.ts
  packages/berlin/src/data/publicGroups.ts
  packages/berlin/src/pages/PublicGroupRegistration.tsx
  packages/berlin/src/pages/SecretGroupRegistration.tsx
Labels: priority, berlin

#491 Fix available hearts
  packages/berlin/src/pages/Comments.tsx
  packages/berlin/src/pages/Cycle.tsx
  packages/berlin/src/store/index.ts
  packages/berlin/src/utils/constants.ts
Labels: bug

#498 493 change author to lead in header
  packages/berlin/src/components/columns/cycle-columns/CycleColumns.styled.tsx
  packages/berlin/src/components/columns/cycle-columns/CycleColumns.tsx
  packages/berlin/src/pages/Cycle.tsx
Labels: easy, berlin, improvement

#496 495 kill header to give more space
  packages/berlin/src/components/header/Header.tsx
Labels: berlin, improvement

#499 492 change co authors
  packages/berlin/src/components/option-card/OptionCard.tsx
  packages/berlin/src/pages/Comments.tsx
  packages/berlin/src/pages/Cycle.tsx
Labels: easy, berlin, improvement

#500 468 update alerts in realtime
  packages/berlin/src/components/header/Header.tsx
Labels: priority, easy, berlin, improvement

#504 add co authors to comments
  packages/berlin/src/pages/Comments.tsx
Labels: improvement

#503 Diego/sorting improvement
  packages/berlin/src/pages/Cycle.tsx
Labels: improvement

#482 473 order by amount of hearts user has allocated
  packages/berlin/src/pages/Cycle.tsx
Labels: priority, easy, berlin

#506 update hearts to 80
  packages/berlin/src/utils/constants.ts
  packages/berlin/src/utils/voting.ts
Labels: feature

#507 Order alerts navbar
  packages/berlin/src/components/header/Header.tsx
Labels: feature

#509 505 add polling to comments
  packages/berlin/src/pages/Comments.tsx
Labels: easy, berlin, improvement

#508 449 show registrations for group
  packages/api/src/fetchGroupRegistrations.ts
  packages/api/src/index.ts
  packages/api/src/types/GroupRegistrationsType.ts
  packages/api/src/types/index.ts
  packages/berlin/src/components/tables/groups-table/GroupsTable.styled.tsx
  packages/berlin/src/components/tables/groups-table/GroupsTable.tsx
  packages/berlin/src/pages/SecretGroupRegistration.tsx
Labels: feature, priority, berlin

#510 462 update cycles in event page in realtime
  packages/berlin/src/pages/Event.tsx
Labels: easy, berlin

#518 Fix alert joining group
  packages/berlin/src/pages/SecretGroupRegistration.tsx
Labels: bug

#519 Remove berlin types
  packages/berlin/src/pages/Account.tsx
  packages/berlin/src/pages/Comments.tsx
  packages/berlin/src/pages/Cycle.tsx
  packages/berlin/src/pages/Event.tsx
  packages/berlin/src/pages/Register.tsx
  packages/berlin/src/types/ButtonType.ts
  packages/berlin/src/types/CycleType.ts
  packages/berlin/src/types/DBEventType.ts
  packages/berlin/src/types/ForumQuestionType.ts
  packages/berlin/src/types/GroupType.ts
  packages/berlin/src/types/RegistrationFieldOptionType.ts
  packages/berlin/src/types/RegistrationFieldType.ts
  packages/berlin/src/types/RegistrationType.ts
  packages/berlin/src/types/UserAttributesType.ts
  packages/core/src/types/AuthUserType.ts
Labels: improvement

#520 517 protect results page
  packages/berlin/src/App.tsx
  packages/berlin/src/components/back-button/BackButton.tsx
  packages/berlin/src/pages/Cycle.tsx
Labels: berlin, improvement

#521 516 order registration data in groups table in secret groups page
  packages/api/src/fetchGroupRegistrations.ts
  packages/api/src/types/GroupRegistrationsType.ts
  packages/berlin/src/components/containers/FlexColumn.styled.tsx
  packages/berlin/src/components/dialog/Dialog.tsx
  packages/berlin/src/components/event-card/EventCard.styled.tsx
  packages/berlin/src/components/footer/Footer.styled.tsx
  packages/berlin/src/components/input/Input.tsx
  packages/berlin/src/components/option-card/OptionCard.tsx
  packages/berlin/src/components/select/Select.styled.tsx
  packages/berlin/src/components/tables/cycle-table/CycleTable.styled.tsx
  packages/berlin/src/components/tables/cycle-table/CycleTable.tsx
  packages/berlin/src/components/tables/groups-table/GroupsTable.styled.tsx
  packages/berlin/src/components/tables/groups-table/GroupsTable.tsx
  packages/berlin/src/components/tables/results-table/ResultsTable.tsx
  packages/berlin/src/components/textarea/Textarea.tsx
  packages/berlin/src/components/voting-cards/VotingCards.tsx
  packages/berlin/src/pages/Account.tsx
  packages/berlin/src/pages/Comments.tsx
  packages/berlin/src/pages/Cycle.tsx
  packages/berlin/src/pages/DataPolicy.tsx
  packages/berlin/src/pages/Event.tsx
  packages/berlin/src/pages/Events.tsx
  packages/berlin/src/pages/Holding.tsx
  packages/berlin/src/pages/Landing.tsx
  packages/berlin/src/pages/Onboarding.tsx
  packages/berlin/src/pages/PublicGroupRegistration.tsx
  packages/berlin/src/pages/Register.tsx
  packages/berlin/src/pages/Results.tsx
  packages/berlin/src/pages/SecretGroupRegistration.tsx
Labels: priority, berlin

#526 Dropdown improvement
  packages/berlin/src/pages/Register.tsx
Labels: feature

#524 add lead author to groups table
  packages/berlin/src/components/tables/groups-table/GroupsTable.styled.tsx
  packages/berlin/src/components/tables/groups-table/GroupsTable.tsx
Labels: feature

#533 523 change default page on login
  packages/berlin/src/App.tsx
Labels: easy, improvement

#535 530 option user endpoint
  packages/berlin/src/components/option-card/OptionCard.tsx
  packages/berlin/src/pages/Comments.tsx
Labels: bug, improvement

#534 528 group members should be shown in a column
  packages/berlin/src/components/button/Button.styled.tsx
  packages/berlin/src/components/button/Button.tsx
  packages/berlin/src/components/button/Button.types.ts
  packages/berlin/src/components/columns/groups-columns/GroupsColumns.styled.tsx
  packages/berlin/src/components/columns/groups-columns/GroupsColumns.tsx
  packages/berlin/src/components/tables/groups-table/GroupsTable.styled.tsx
  packages/berlin/src/components/tables/groups-table/GroupsTable.tsx
  packages/berlin/src/data/groups.ts
  packages/berlin/src/pages/SecretGroupRegistration.tsx
Labels: improvement

#537 fix initial registration
  packages/berlin/src/pages/Register.tsx
Labels: bug

#540 536 add funding endpoint
  packages/api/src/fetchForumQuestionFunding.ts
  packages/api/src/index.ts
  packages/api/src/types/FundingType.ts
  packages/api/src/types/index.ts
  packages/berlin/src/App.tsx
  packages/berlin/src/components/columns/results-columns/ResultsColumns.styled.tsx
  packages/berlin/src/components/columns/results-columns/ResultsColumns.tsx
  packages/berlin/src/components/tables/results-table/ResultsTable.styled.tsx
  packages/berlin/src/components/tables/results-table/ResultsTable.tsx
  packages/berlin/src/pages/Results.tsx
  packages/berlin/src/utils/constants.ts
Labels: berlin, improvement

#541 new proposal dropdown title format
  packages/berlin/src/pages/Register.tsx
Labels: feature

#542 fix comments page
  packages/api/src/types/QuestionOptionType.ts
  packages/berlin/src/components/tables/comment-table/CommentsTable.tsx
  packages/berlin/src/pages/Comments.tsx
Labels: bug

#549 543 show message when no proposals
  packages/berlin/src/components/tables/groups-table/GroupsTable.tsx
Labels: improvement

#547 545 remove date from comments page
  packages/berlin/src/components/columns/comments-columns/CommentsColumns.styled.tsx
  packages/berlin/src/components/columns/comments-columns/CommentsColumns.tsx
  packages/berlin/src/components/tables/comment-table/CommentsTable.tsx
Labels: improvement

#548 544 trim title and descriptions
  packages/berlin/src/pages/Register.tsx
Labels: improvement

#554 add funding request to vote page
  packages/api/src/types/CycleType.ts
  packages/berlin/src/components/option-card/OptionCard.tsx
  packages/berlin/src/pages/Cycle.tsx
Labels: feature

#556 546 improve lighthouse score
  packages/berlin/index.html
  packages/berlin/public/robots.txt
  packages/berlin/src/components/header/Header.tsx
Labels: berlin, improvement

#557 fix empty string not throwing error on number field
  packages/berlin/src/pages/Register.tsx
Labels: bug

#562 561 redirect to results when cycle closes
  packages/berlin/src/components/header/Header.tsx
  packages/berlin/src/pages/Cycle.tsx
  packages/berlin/src/pages/Results.tsx
Labels: improvement

#565 564 make public group select title more general
  packages/berlin/src/pages/PublicGroupRegistration.tsx
Labels: improvement

#568 567 change minimum funding to $250
  packages/berlin/src/pages/Register.tsx
Labels: improvement

#566 Fix nav links on mobile
  packages/berlin/src/components/header/Header.tsx
Labels: bug, berlin

#570 569 update secret groups page
  packages/berlin/src/data/groups.ts
  packages/berlin/src/pages/SecretGroupRegistration.tsx
Labels: improvement

#572 571 update final question constant
  packages/berlin/src/utils/constants.ts
Labels: improvement

#573 Minor fixes
  packages/berlin/src/components/columns/comments-columns/CommentsColumns.styled.tsx
  packages/berlin/src/components/tables/comment-table/CommentsTable.styled.tsx
  packages/berlin/src/components/tables/comment-table/CommentsTable.tsx
  packages/berlin/src/pages/Cycle.tsx
Labels: improvement

#578 Show lead author at results table
  packages/berlin/src/components/tables/results-table/ResultsTable.tsx
Labels: improvement
