Repository lexicongovernance/pluraltools-frontend, pull requests merged in 2024-01, with the labels that each got.

#32 add .env skeleton and readme with getting started
  .env
  README.md
Labels: documentation

#33 Home api connection
  package.json
  pnpm-lock.yaml
  src/api/fetchCycles.ts
  src/api/fetchNonce.ts
  src/api/fetchOptions.ts
  src/api/fetchRegistration.ts
  src/api/fetchUserVotes.ts
  src/api/postVote.ts
  src/components/header/Header.tsx
  src/components/option/Option.styled.tsx
  src/components/option/Option.tsx
  src/components/zupassLoginButton/ZupassLoginButton.tsx
  src/hooks/useCountdown.tsx
  src/layout/Layout.styled.tsx
  src/main.tsx
  src/pages/Home.tsx
  src/pages/Register.tsx
  src/types/CycleType.ts
Labels: enhancement

#36 Dynamic register page
  package.json
  pnpm-lock.yaml
  src/api/fetchEvents.ts
  src/api/fetchGroups.ts
  src/api/fetchRegistration.ts
  src/api/fetchRegistrationData.ts
  src/api/fetchRegistrationFields.ts
  src/api/fetchRegistrationOptions.ts
  src/api/index.ts
  src/api/postRegistration.ts
  src/api/postRegistrationFields.ts
  src/hooks/useGroups.tsx
  src/pages/Register.tsx
  src/types/DBEventType.ts
  src/types/ProposalType.ts
  src/types/RegistrationDataType.ts
  src/types/RegistrationFieldOptionType.ts
  src/types/RegistrationFieldType.ts
  src/types/RegistrationOption.ts
  src/types/RegistrationType.ts
Labels: enhancement

#38 Refactor registration field required property
  src/pages/Register.tsx
  src/types/RegistrationFieldType.ts
Labels: bug

#42 Migrate from react-hook-form to Tanstack form
  package.json
  pnpm-lock.yaml
  src/api/fetchRegistration.ts
  src/api/index.ts
  src/api/postRegistrationData.ts
  src/pages/Register.tsx
Labels: enhancement

#44 Fix home page
  src/App.tsx
  src/components/zupassLoginButton/ZupassLoginButton.tsx
  src/store.ts
Labels: bug

#45 Disable save all button
  src/pages/Home.tsx
Labels: enhancement

#43 Account page
  src/App.tsx
  src/api/fetchGroups.ts
  src/api/fetchUserGroups.ts
  src/api/updateUserData.ts
  src/components/header/Header.tsx
  src/layout/Layout.tsx
  src/pages/Account.tsx
  src/pages/Home.tsx
  src/pages/Register.tsx
  src/types/GroupType.ts
Labels: enhancement

#49 Add fetchForumQuestionStatistics API
  src/api/fetchForumQuestionStatistics.ts
  src/api/index.ts
  src/types/ForumQuestionType.ts
Labels: enhancement

#51 Results page
  public/icons/bronze_badge.svg
  public/icons/gold_badge.svg
  public/icons/silver_badge.svg
  src/components/card/Card.tsx
  src/components/chip/Chip.styled.tsx
  src/pages/Results.tsx
Labels: enhancement

#55 Fix stale time event query
  src/pages/Event.tsx
Labels: bug

#53 Add event description to event card
  src/pages/Event.tsx
Labels: enhancement

#54 Rename groups to affiliation
  src/pages/Account.tsx
Labels: enhancement

#56 Design system typography
  src/components/chip/Chip.styled.tsx
  src/components/typography/Body.tsx
  src/components/typography/Error.tsx
  src/components/typography/Label.tsx
  src/components/typography/Subtitle.tsx
  src/components/typography/Title.tsx
  src/layout/Layout.styled.tsx
  src/pages/Account.tsx
  src/pages/Events.tsx
  src/pages/Register.tsx
  src/pages/Results.tsx
  src/pages/Vote.tsx
  src/types/ForumQuestionType.ts
Labels: enhancement

#57 Demo updates
  public/full_node.png
  public/icons/back_arrow.svg
  public/zuzalu.png
  src/components/eventCard/EventCard.tsx
  src/components/header/Header.styled.tsx
  src/components/header/Header.tsx
  src/data/landing.ts
  src/layout/Layout.styled.tsx
  src/pages/Event.tsx
  src/pages/Events.tsx
  src/pages/Results.tsx
  src/pages/Vote.tsx
Labels: enhancement

#60 Order proposals by plural score
  src/pages/Vote.tsx
Labels: enhancement

#59 Add user attributes
  src/api/fetchUserAttributes.ts
  src/api/updateUserData.ts
  src/pages/Account.tsx
  src/types/UserAttributesType.ts
Labels: enhancement

#61 Refactor imagePicker function and update image paths
  public/berlin.png
  src/pages/Event.tsx
  src/pages/Events.tsx
  src/pages/Vote.tsx
Labels: enhancement

#62 Update diasbled styles
  src/components/button/Button.styled.tsx
Labels: enhancement

#63 Decrease img size
  public/berlin.png
  public/taipei.png
  src/pages/Event.tsx
  src/pages/Vote.tsx
Labels: enhancement

#76 Design system
  index.html
  public/full_node.png
  public/icons/arrow_down.svg
  public/images/astronaut.png
  public/images/berlin.png
  public/images/taipei.png
  public/options.json
  public/zuzalu.png
  src/components/button/Button.styled.tsx
  src/components/button/Button.tsx
  src/components/card/Card.styled.tsx
  src/components/countdown/Countdown.styled.tsx
  src/components/eventCard/EventCard.styled.tsx
  src/components/eventCard/EventCard.tsx
  src/components/footer/Footer.styled.tsx
  src/components/form/ErrorText.tsx
  src/components/form/Label.tsx
  src/components/header/Header.styled.tsx
  src/components/hero/Hero.tsx
  src/components/onboarding/Onboarding.styled.tsx
  src/components/onboarding/Onboarding.tsx
  src/components/option/Option.styled.tsx
  src/components/typography/Body.tsx
  src/components/typography/ButtonText.tsx
  src/components/typography/Error.tsx
  src/components/typography/Heading.tsx
  src/components/typography/Label.tsx
  src/components/typography/Subtext.tsx
  src/components/typography/Subtitle.tsx
  src/index.css
  src/pages/Account.tsx
  src/pages/Event.tsx
  src/pages/Events.tsx
  src/pages/Landing.tsx
  src/pages/Register.tsx
  src/pages/Results.tsx
  src/types/DBEventType.ts
Labels: enhancement

#79 Revamp account registration
  index.html
  package.json
  pnpm-lock.yaml
  src/components/form/Input.tsx
  src/components/form/Select.tsx
  src/components/header/Header.tsx
  src/pages/Account.tsx
  src/pages/Register.tsx
Labels: enhancement

#84 Searchable select component
  src/components/select/Select.styled.tsx
  src/components/select/Select.tsx
  src/components/select/index.ts
Labels: enhancement

#83 Add Subtitle component to Register page
  src/pages/Register.tsx
  src/types/DBEventType.ts
Labels: enhancement
